---
title: "Check whether results are robust with ordinal model"
author: "Julia Rohrer"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    includes: 
      before_body: nav.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load("prep.RData")
library(haven)
library(marginaleffects)
library(brms)
# Function wants a factor as outcome
combined$source <- as.factor(combined$source)

```

## Do we get the same pattern if we once again use an ordinal model?

```{r ordinal}

# Fit model in ordinal
# We are using brms here simply because polr() does not support
# the postestimation routine of marginaleffects on the link scale
library(splines)
# explanandum_paper_only_ordinal <- brm(satis ~ as.factor(year) + gender + as.factor(year):gender +
#                                     bs(age, df = 3) + as.factor(year):bs(age, df = 3) + gender:bs(age, df = 3) + as.factor(year):gender:bs(age, df = 3) +
#                                     as.factor(schooltype) + as.factor(year):as.factor(schooltype) + gender:as.factor(schooltype) + as.factor(year):gender:as.factor(schooltype) +
#                                     as.factor(mig_lang) + as.factor(year):as.factor(mig_lang) + gender:as.factor(mig_lang) + as.factor(year):gender:as.factor(mig_lang),
#                                   family = cumulative("probit"),
#                                   cores = 4,
#                    data = combined[combined$source == "paper",])
#  
# 
# saveRDS(explanandum_paper_only_ordinal, file = "explanandum_paper_only_ordinal")
explanandum_paper_only_ordinal <- readRDS("explanandum_paper_only_ordinal")

# Demographics like in 2010
temp1 <- combined[combined$year == 2010,]
temp1$year <- 2010
temp2 <- combined[combined$year == 2010,]
temp2$year <- 2015
temp3 <- combined[combined$year == 2010,]
temp3$year <- 2023
all2010 <- rbind(temp1, temp2, temp3)

# Predicted values for all combinations of gender and year
pred <- avg_predictions(explanandum_paper_only_ordinal,
                 by = c("gender", "year"),
                 newdata = all2010,
                 vcov = ~ unique_classroom,
                 type = "link")
print(pred)

# Counterfactual comparisons: latent gender gaps per year
comps <- avg_comparisons(explanandum_paper_only_ordinal, variables = "gender", by = "year",
                 newdata = all2010,
                 vcov = ~ unique_classroom,
                 type = "link")
print(comps)

# Let's compare the 2010 and 2023 gender gaps
max_comp <- avg_comparisons(explanandum_paper_only_ordinal, variables = "gender", by = "year",
                hypothesis = "b1 = b3",
                 newdata = all2010,
                vcov = ~ unique_classroom,
                 type = "link")
print(max_comp)


# And lets look at how these vary by migration background

# Widening of gender gap for students without migration background
print(avg_comparisons(explanandum_paper_only_ordinal, variables = "gender", by = c("year", "mig_lang"),
                 newdata = all2010,
                 vcov = ~ unique_classroom,
                 hypothesis = "b1 = b5",
                 type = "link"))

# Widening of gender gap for students with migration background
print(avg_comparisons(explanandum_paper_only_ordinal, variables = "gender", by = c("year", "mig_lang"),
                 newdata = all2010,
                 vcov = ~ unique_classroom,
                 hypothesis = "b2 = b6",
                 type = "link"))
# Comparing the widening (triple-interaction gender, year, migration background)
print(avg_comparisons(explanandum_paper_only_ordinal, variables = "gender", by = c("year", "mig_lang"),
                 newdata = all2010,
                 vcov = ~ unique_classroom,
                 hypothesis = "b1 - b5 = b2 - b6",
                 type = "link"))
```





