---
title: "Check whether results are robust with ordinal model"
author: "Julia Rohrer"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load("synthetic_data")
combined <- syn_dat

library(haven)
library(marginaleffects)
library(brms)
# Function wants a factor as outcome
combined$source <- as.factor(combined$source)

```

## Do we get the same pattern if we once again use an ordinal model?

```{r ordinal}

# Fit model in ordinal
# We are using brms here simply because polr() does not support
# the postestimation routine of marginaleffects on the link scale
explanandum_paper_only_ordinal <- brm(satis ~ as.factor(year) + gender + as.factor(year):gender +
                                        as.factor(age) + as.factor(year):as.factor(age) + gender:as.factor(age) + as.factor(year):gender:as.factor(age) +
                                       as.factor(schooltype) + as.factor(year):as.factor(schooltype) + gender:as.factor(schooltype) + as.factor(year):gender:as.factor(schooltype) +
                                        as.factor(mig_lang) + as.factor(year):as.factor(mig_lang) + gender:as.factor(mig_lang) + as.factor(year):gender:as.factor(mig_lang), 
                                 family = cumulative("probit"),
                                 cores = 4,
                  data = combined[combined$source == "paper",])
# saveRDS(explanandum_paper_only_ordinal, file = "explanandum_paper_only_ordinal")
# explanandum_paper_only_ordinal <- readRDS("explanandum_paper_only_ordinal")

# Demographics like in 2023
temp1 <- combined[combined$year == 2023,]
temp1$year <- 2010
temp2 <- combined[combined$year == 2023,]
temp2$year <- 2015
temp3 <- combined[combined$year == 2023,]
temp3$year <- 2023
all2023 <- rbind(temp1, temp2, temp3)


pred <- avg_predictions(explanandum_paper_only_ordinal,
                 by = c("gender", "year"),
                 newdata = all2023,
                 type = "link")

comps <- avg_comparisons(explanandum_paper_only_ordinal, variables = "gender", by = "year",
                 newdata = all2023,
                 type = "link")
print(comps)

max_comp <- avg_comparisons(explanandum_paper_only_ordinal, variables = "gender", by = "year",
                hypothesis = "b1 = b3",
                 newdata = all2023,
                 type = "link")
print(max_comp)



# 2023
print(avg_comparisons(explanandum_paper_only_ordinal, variables = "gender", by = c("year", "mig_lang"),
                 newdata = all2023,
      hypothesis = "b1 = b5",
                 type = "link"))


# 2023
print(avg_comparisons(explanandum_paper_only_ordinal, variables = "gender", by = c("year", "mig_lang"),
                 newdata = all2023,
                 hypothesis = "b2 = b6",
                 type = "link"))
# Comparison
print(avg_comparisons(explanandum_paper_only_ordinal, variables = "gender", by = c("year", "mig_lang"),
                 newdata = all2023,
                 hypothesis = "b1 - b5 = b2 - b6",
                 type = "link"))
```





